.phony: run

run:
	@echo
	@echo small problem
	python3 src/knapsack01.py data/small.txt
	@echo
	@echo medium problem
	python3 src/knapsack01.py data/medium.txt
	@echo
	@echo large problem
	python3 src/knapsack01.py data/large.txt
